### ISSUE TITLE
Uploading Activities

### ISSUE THREAD

**Issue by app4g** [felipeam86/garpyclient#11]
I know your current garpyClient and garpy project does not have any functionality to do files upload to Garmin Connect, but is the capability to do that available w/ some coding? This is not using any official Garmin API I presume? (not that I can see from the codes)

But this is basically emulating actions on a Garmin's Webpage right?

out of the many projects which I looked at, yours is the first that actually is able to get me logged into Garmin Connect w/o any authentication errors.

**Comment by felipeam86** [comment]
Hi @app4g 

This is not something I intend to add to the library. I do not have a use case or means of testing it.

You mention that you have tried many projects before mine. Have you tried [garminexport](https://github.com/petergardfjall/garminexport)? It has an upload method.

If you cannot manage to authenticate with garminexport, you can borrow the method from garminexport and use the garpy client instead. This is the method I am talking about: https://github.com/petergardfjall/garminexport/blob/21e11338f277952dec1c92725a2ca5b6cad59b8c/garminexport/garminclient.py#L445

It looks fairly simple to replicate.

**Comment by app4g** [comment]
I can confirm that garminexport works. (at least some of the time)
tho the upload still marks as failed (403) although its uploaded.

tx for your help/point in right direction. I will look at how to integrate it,
